GET http://localhost:3005/products
###
POST http://localhost:3005/products
Content-Type: application/json

{
"id": 3,
"image_url": "https://cdn.barbora.lt/products/7012d88a-73ed-4e36-9c7c-18ef3ed440d6_m.png", 
"title": "Slyviniai pomidorai (57-67 mm), 1 kg", "description": "Slyviniai pomidorai (1 kl.) savo forma ir dydžiu primena slyvas, jų minkštimas yra mėsingas ir su mažai sėklelių.",
"price": 2.39
}